// Code generated by generate_style.go; DO NOT EDIT.
package textstyle

const (
	BOLD_LOWER_OFFSET       = 119737
	BOLD_UPPER_OFFSET       = 119743
	BOLD_DIGIT_OFFSET       = 120734
	ITALIC_LOWER_OFFSET     = 119789
	ITALIC_UPPER_OFFSET     = 119795
	ITALIC_DIGIT_OFFSET     = 0
	SANS_SERIF_LOWER_OFFSET = 120153
	SANS_SERIF_UPPER_OFFSET = 120159
	SANS_SERIF_DIGIT_OFFSET = 120754
)

func Bold() *Transformer {
	return NewTransformer(
		NewSimpleReplacer(
			"Bold",
			BOLD_LOWER_OFFSET,
			BOLD_UPPER_OFFSET,
			BOLD_DIGIT_OFFSET,
		),
	)
}

func Italic() *Transformer {
	return NewTransformer(
		NewSimpleReplacer(
			"Italic",
			ITALIC_LOWER_OFFSET,
			ITALIC_UPPER_OFFSET,
			ITALIC_DIGIT_OFFSET,
		),
	)
}

func SansSerif() *Transformer {
	return NewTransformer(
		NewSimpleReplacer(
			"SansSerif",
			SANS_SERIF_LOWER_OFFSET,
			SANS_SERIF_UPPER_OFFSET,
			SANS_SERIF_DIGIT_OFFSET,
		),
	)
}
